### PR TITLE
Fix issue when no database is available

### PR DESCRIPTION
**Pull request by armandfardeau**
When building docker images, no database is available therefore an error is raised.

This P.R. rescue from this case

### CODE REVIEW

**Comment by ahukkanen** [comment]
Thanks for the PR @armandfardeau !

Could you add a test case as well please? Preferably so that this exception would be raised naturally by Rails, e.g. by changing the database configuration during that test.

**Comment by armandfardeau** [comment]
> Thanks for the PR @armandfardeau !
> 
> Could you add a test case as well please? Preferably so that this exception would be raised naturally by Rails, e.g. by changing the database configuration during that test.

Absolutely, I was working on it !

**Comment by armandfardeau** [comment]
I can't test the configuration directly, by modifying the DATABASE_HOST environment variable I get the same error than specified in the test (ActiveRecord::StatementInvalid), on the other hand by trying to build a docker image without the environment variable, I get the error I'm rescuing (ActiveRecord::ConnectionNotEstablished).  The introduction of the fix solves this problem. If you have any ideas I'm interested.

For further references, this happens when initializing the application.

**Comment by armandfardeau** [comment]
@ahukkanen Feel free to restart actions, it seems that Github had an outage last night.

**Pull request closed without merging**
